package eu.epfc.anc3.model;

public enum ImageType {
    CARROT_STATE1_IMAGE, CARROT_STATE2_IMAGE, CARROT_STATE3_IMAGE, CARROT_STATE4_IMAGE, CARROT_STATEROTTEN_IMAGE, NOIMAGE,
    CABBAGE_STATE1_IMAGE, CABBAGE_STATE2_IMAGE, CABBAGE_STATE3_IMAGE, CABBAGE_STATE4_IMAGE, CABBAGE_STATEROTTEN_IMAGE,
    GRASS_IMAGE
}
